# version: '3.1'

# services:
#     mongo:
#         image: mongo
#         restart: always
#         environment:
#             MONGO_INITDB_ROOT_USERNAME: dj19
#             MONGO_INITDB_ROOT_PASSWORD: aa09094553940

#     web:
#         build: .    
#         volumes:
#             - .:/usr/src/app
#         ports:
#             - "8000:8000"
# version: '3'

# services:
#     db:
#         image: postgres
#         # environment:
#     #         POSTGRES_PASSWORD: mydb        
#         environment:
#             POSTGRES_USER: djangouser
#             POSTGRES_PASSWORD: djangopassword
        
#     # web:
#     #     build: .
#     #     volumes:
#     #         - .:/usr/src/webpage
#     #     ports:
#     #         - "8000:8000"

#     # environment:

services:
  django:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      shm_size: 16g
    ports:
      - mode: ingress
        target: 8000
        # published: 8000 # uncomment for local dev
    environment:
      - DEBUG=False # set to "True" for local dev
    #deploy:
    #  resources:
    #    reservations:
    #      memory: 256M`


            