version: '3.1'

services:
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: dj19
            MONGO_INITDB_ROOT_PASSWORD: aa09094553940

    web:
        build: .    
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"