# Generated by Django 3.2.6 on 2022-04-03 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ship_san_diego', '0002_comment_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysandiegodays',
            name='dateNow',
            field=models.DateField(default=datetime.datetime(2022, 4, 3, 3, 3, 27, 811733)),
        ),
    ]
