# Generated by Django 3.2.6 on 2021-12-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_freedive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_rooms', models.IntegerField(default=1)),
                ('message', models.TextField(blank=True)),
                ('sender', models.CharField(max_length=64)),
                ('sender_image', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images')),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.CharField(max_length=64)),
                ('participant_image', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='event_cost',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='events',
            name='event_image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='organizer_contact',
            field=models.CharField(default=11, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='organizer_image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='event_participants',
            field=models.ManyToManyField(to='app_freedive.Participants'),
        ),
    ]
