# Generated by Django 3.2.6 on 2021-12-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_freedive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='organizer_contact',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='organizer_image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
