# Generated by Django 3.2.6 on 2021-12-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_freedive', '0002_auto_20211215_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_cost',
            field=models.IntegerField(default=1),
        ),
    ]
