# Generated by Django 3.2.6 on 2021-12-15 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_freedive', '0003_events_event_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
