# Generated by Django 3.2.6 on 2021-12-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_freedive', '0005_event_chat_event_room_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_participants',
            field=models.ManyToManyField(to='app_freedive.Participants'),
        ),
        migrations.AlterField(
            model_name='event_room',
            name='room_participants',
            field=models.ManyToManyField(to='app_freedive.Participants'),
        ),
    ]
