# Generated by Django 3.2.6 on 2021-12-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_freedive', '0006_auto_20211216_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='participant_image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Event_Room',
        ),
    ]
