# Generated by Django 3.2.6 on 2021-12-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_freedive', '0007_auto_20211216_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images')),
            ],
        ),
        migrations.AlterField(
            model_name='event_chat',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
