# Generated by Django 3.2.6 on 2021-12-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_rooms', models.IntegerField(default=1)),
                ('message', models.TextField(blank=True)),
                ('sender', models.CharField(max_length=64)),
                ('sender_image', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images')),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.CharField(max_length=64)),
                ('participant_image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=64)),
                ('end_time', models.CharField(max_length=64)),
                ('organizer', models.CharField(max_length=64)),
                ('organizer_contact', models.CharField(max_length=64)),
                ('organizer_image', models.URLField()),
                ('event_type', models.CharField(max_length=64)),
                ('event_description', models.CharField(max_length=500)),
                ('event_name', models.CharField(max_length=64)),
                ('event_image', models.URLField()),
                ('event_cost', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_participants', models.ManyToManyField(to='app_event.Participants')),
            ],
        ),
    ]
