# Generated by Django 3.2.2 on 2021-08-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('player', models.CharField(blank=True, max_length=64)),
                ('message', models.CharField(blank=True, max_length=64)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, max_length=64)),
                ('player', models.CharField(blank=True, max_length=64)),
                ('user', models.CharField(blank=True, max_length=64)),
                ('sticker', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('host', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.IntegerField(blank=True)),
                ('player1', models.CharField(blank=True, max_length=64)),
                ('player2', models.CharField(blank=True, max_length=64)),
                ('full', models.BooleanField(default=False)),
                ('sticker1', models.CharField(blank=True, max_length=64)),
                ('sticker2', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
