# Generated by Django 3.2.2 on 2021-08-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_street_race', '0002_auto_20210809_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='full',
            field=models.BooleanField(default=False),
        ),
    ]
