# Generated by Django 3.2.2 on 2021-08-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_street_race', '0003_room_full'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('message', models.CharField(blank=True, max_length=64)),
                ('player', models.ManyToManyField(to='a_street_race.Room')),
            ],
        ),
    ]
