# Generated by Django 3.2.2 on 2021-08-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_street_race', '0004_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='player',
        ),
        migrations.AddField(
            model_name='chat',
            name='player',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
