# Generated by Django 3.2.2 on 2021-08-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_street_race', '0005_auto_20210811_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, max_length=64)),
                ('player', models.CharField(blank=True, max_length=64)),
                ('user', models.CharField(blank=True, max_length=64)),
                ('sticker', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.IntegerField(blank=True),
        ),
    ]
