# Generated by Django 3.2.2 on 2021-08-15 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('a_street_race', '0006_auto_20210815_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='sticker1',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='room',
            name='sticker2',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
