# Generated by Django 3.2.2 on 2021-08-16 23:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('a_street_race', '0007_auto_20210816_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
