# Generated by Django 3.2.2 on 2021-08-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_street_race', '0008_alter_chat_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default='2021-08-17'),
        ),
    ]
