# Generated by Django 3.2.6 on 2021-08-25 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('g_pigeon_race', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='entry',
            field=models.ManyToManyField(blank=True, related_name='entry', to='user.Mypigeons'),
        ),
        migrations.AddField(
            model_name='lap',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='L', to='g_pigeon_race.race'),
        ),
        migrations.AddField(
            model_name='lap',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LL', to='g_pigeon_race.point'),
        ),
    ]
