# Generated by Django 3.2.6 on 2021-09-28 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('g_pigeon_race', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='release',
        ),
        migrations.AddField(
            model_name='lap',
            name='char_time',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='race',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='race',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='release2',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lap',
            name='release_time',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='loaded',
            name='clock_time',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='loaded',
            name='release_time',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='record',
            name='clock',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
