# Generated by Django 3.2.6 on 2021-09-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_pigeon_race', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
