# Generated by Django 3.2.6 on 2021-09-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_pigeon_race', '0003_auto_20210928_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='release2',
            field=models.IntegerField(),
        ),
    ]
