# Generated by Django 3.2.6 on 2021-12-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_pigeon_race', '0003_auto_20211020_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap', models.IntegerField()),
                ('place', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('time', models.CharField(max_length=64)),
            ],
        ),
    ]
