# Generated by Django 3.2.6 on 2021-09-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_pigeon_race', '0003_race_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
