# Generated by Django 3.2.6 on 2021-09-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_pigeon_race', '0004_race_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='clock',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
