# Generated by Django 3.2.6 on 2021-09-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_pigeon_race', '0004_alter_record_release2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='release2',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='speed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.IntegerField(),
        ),
    ]
