# Generated by Django 3.2.6 on 2021-09-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_pigeon_race', '0005_alter_record_clock'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='char_time',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='lap',
            name='release_time',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='loaded',
            name='release_time',
            field=models.IntegerField(default=1),
        ),
    ]
