# Generated by Django 3.2.6 on 2021-09-28 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('g_pigeon_race', '0005_auto_20210928_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='release2',
        ),
        migrations.AddField(
            model_name='record',
            name='release',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='clock',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
