# Generated by Django 3.2.6 on 2021-09-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_pigeon_race', '0006_auto_20210928_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='clock',
            field=models.DateTimeField(max_length=64),
        ),
    ]
