# Generated by Django 3.2.6 on 2021-09-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_pigeon_race', '0007_auto_20210928_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='release',
            field=models.DateField(blank=True),
        ),
    ]
