# Generated by Django 3.2.6 on 2021-09-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_pigeon_race', '0008_alter_record_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='release',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
