# Generated by Django 3.2.6 on 2021-10-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_pigeon_race', '0008_auto_20210928_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaded',
            name='isLoaded',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.CharField(max_length=64),
        ),
    ]
