# Generated by Django 3.2.6 on 2021-10-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_pigeon_race', '0009_auto_20211001_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='num_load',
            field=models.ManyToManyField(blank=True, related_name='load_count', to='g_pigeon_race.Loaded'),
        ),
    ]
