# Generated by Django 3.2.6 on 2021-10-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_pigeon_race', '0010_lap_num_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='pigeon_id',
            field=models.IntegerField(default=1),
        ),
    ]
