# Generated by Django 3.2.6 on 2021-10-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_pigeon_race', '0011_record_pigeon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lap',
            name='release_time',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='loaded',
            name='release_time',
            field=models.IntegerField(blank=True),
        ),
    ]
