# Generated by Django 3.2.6 on 2021-10-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_pigeon_race', '0012_auto_20211003_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaded',
            name='release_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
