# Generated by Django 3.2.6 on 2021-10-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_pigeon_race', '0013_alter_loaded_release_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.IntegerField()),
                ('pigeon_id', models.IntegerField()),
                ('pigeon_name', models.CharField(max_length=64)),
                ('tspeed', models.IntegerField()),
            ],
            options={
                'ordering': ['-tspeed'],
            },
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-speed']},
        ),
        migrations.AlterField(
            model_name='lap',
            name='release_time',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='loaded',
            name='release_time',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
