# Generated by Django 3.2.6 on 2021-10-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('instructor', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=500)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('courses', models.ManyToManyField(blank=True, related_name='enrollee', to='app_course_booking.Book')),
            ],
        ),
    ]
