# Generated by Django 3.2.6 on 2021-09-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('instructor', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
