# Generated by Django 3.2.6 on 2021-09-06 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_course_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
