# Generated by Django 3.2.6 on 2021-09-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_course_booking', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='enrollee', to='app_course_booking.Book'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.CharField(max_length=64),
        ),
    ]
