# Generated by Django 3.2.6 on 2021-08-30 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tally',
            name='date',
            field=models.TextField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tally',
            name='day',
            field=models.TextField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tally',
            name='noon',
            field=models.TextField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
