# Generated by Django 3.2.6 on 2021-08-30 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_food', '0004_auto_20210830_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='tally',
            name='eve',
            field=models.TextField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='tally',
            name='am',
            field=models.TextField(blank=True, default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tally',
            name='pm',
            field=models.TextField(blank=True, default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
