# Generated by Django 3.2.6 on 2021-08-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_food', '0005_auto_20210830_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally',
            name='am',
            field=models.TextField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tally',
            name='eve',
            field=models.TextField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tally',
            name='pm',
            field=models.TextField(blank=True, max_length=64, null=True),
        ),
    ]
