# Generated by Django 3.2.6 on 2021-08-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_food', '0007_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='date',
            field=models.TextField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='gabi',
            field=models.TextField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='tanghali',
            field=models.TextField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='umaga',
            field=models.TextField(max_length=64, null=True),
        ),
    ]
