# Generated by Django 3.2.6 on 2021-08-30 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_food', '0008_auto_20210830_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='date',
            field=models.TextField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='gabi',
            field=models.TextField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='tanghali',
            field=models.TextField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='umaga',
            field=models.TextField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
