# Generated by Django 3.2.6 on 2021-08-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_food', '0010_rename_date_food_sdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='sdate',
            new_name='date',
        ),
    ]
