# Generated by Django 3.2.6 on 2021-08-30 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_food', '0011_rename_sdate_food_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cook',
            field=models.TextField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='g_cost',
            field=models.TextField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='t_cost',
            field=models.TextField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='u_cost',
            field=models.TextField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
