# Generated by Django 3.2.6 on 2021-08-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_food', '0012_auto_20210830_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='tally',
            name='date',
            field=models.TextField(default=3108, max_length=64),
            preserve_default=False,
        ),
    ]
