# Generated by Django 3.2.6 on 2021-12-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_blog', '0002_blog_item_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_item',
            name='publisher',
            field=models.CharField(default='user', max_length=64),
        ),
    ]
