# Generated by Django 3.2.6 on 2022-05-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateN', models.IntegerField()),
                ('monthN', models.IntegerField()),
                ('time', models.TimeField()),
                ('departFrom', models.CharField(max_length=84)),
                ('contactNumber', models.CharField(max_length=94)),
                ('otherDetails', models.TextField(blank=True)),
            ],
        ),
    ]
