# Generated by Django 3.2.6 on 2022-05-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Car', '0002_placeschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeschedule',
            name='monthN',
            field=models.IntegerField(choices=[('1', 'GREEN'), ('2', 'BLUE'), ('3', 'RED'), ('4', 'ORANGE'), ('5', 'BLACK')]),
        ),
    ]
