# Generated by Django 3.2.6 on 2022-05-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Car', '0003_alter_placeschedule_monthn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeschedule',
            name='monthN',
            field=models.CharField(choices=[('1', 'GREEN'), ('2', 'BLUE'), ('3', 'RED'), ('4', 'ORANGE'), ('5', 'BLACK')], max_length=95),
        ),
    ]
