# Generated by Django 3.2.6 on 2022-05-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Car', '0004_alter_placeschedule_monthn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeschedule',
            name='time',
        ),
        migrations.AddField(
            model_name='placeschedule',
            name='timeDeparture',
            field=models.CharField(default=1, max_length=94),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placeschedule',
            name='monthN',
            field=models.IntegerField(),
        ),
    ]
