# Generated by Django 3.2.6 on 2022-05-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Car', '0005_auto_20220513_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='placeSchedule',
            field=models.ManyToManyField(blank=True, to='app_Car.PlaceSchedule'),
        ),
    ]
