# Generated by Django 3.2.6 on 2022-05-14 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_Car', '0006_places_placeschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeschedule',
            name='arriveTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goingTo', to='app_Car.places'),
        ),
        migrations.AlterField(
            model_name='places',
            name='placeSchedule',
            field=models.ManyToManyField(blank=True, related_name='scheds', to='app_Car.PlaceSchedule'),
        ),
    ]
