# Generated by Django 3.2.6 on 2022-05-14 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_Car', '0007_auto_20220514_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeschedule',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='placeschedule',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
