# Generated by Django 3.2.6 on 2022-05-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Car', '0010_remove_placeschedule_monthnn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeschedule',
            name='dateN',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='placeschedule',
            name='monthN',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='placeschedule',
            name='timeDeparture',
            field=models.CharField(blank=True, max_length=94),
        ),
    ]
