# Generated by Django 3.2.6 on 2022-05-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Car', '0011_auto_20220515_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeschedule',
            name='yearN',
            field=models.IntegerField(blank=True, default=22),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placeschedule',
            name='dateN',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
