# Generated by Django 3.2.6 on 2022-05-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_Car', '0012_auto_20220515_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='placeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateN', models.IntegerField(blank=True, null=True)),
                ('monthN', models.IntegerField(blank=True)),
                ('yearN', models.IntegerField(blank=True)),
                ('meetPlace', models.CharField(blank=True, max_length=64)),
                ('meetTime', models.CharField(blank=True, max_length=12)),
                ('endDate', models.CharField(blank=True, max_length=64)),
                ('eventTitle', models.CharField(max_length=94)),
                ('eventCost', models.CharField(max_length=64)),
                ('eventDetails', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('eventPlace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PlaceOfEvent', to='app_Car.places')),
            ],
        ),
        migrations.AddField(
            model_name='places',
            name='placeEvent',
            field=models.ManyToManyField(blank=True, related_name='events', to='app_Car.placeEvent'),
        ),
    ]
