# Generated by Django 3.2.6 on 2021-09-02 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_index', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mymodel',
            new_name='Item',
        ),
    ]
