# Generated by Django 3.2.6 on 2021-09-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
