# Generated by Django 3.2.6 on 2021-09-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_sale', '0004_rename_delivered_item_notavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='link10',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='link2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='link3',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='link4',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='link5',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='link6',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='link7',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='link8',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='link9',
            field=models.URLField(blank=True),
        ),
    ]
