# Generated by Django 3.2.6 on 2021-09-12 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('com_sale', '0005_auto_20210912_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='select',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
