# Generated by Django 3.2.6 on 2021-09-12 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('com_sale', '0007_auto_20210912_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
