# Generated by Django 3.2.6 on 2021-09-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_sale', '0009_order_del_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='del_time',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
