# Generated by Django 3.2.6 on 2021-09-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_sale', '0010_alter_order_del_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='del_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
