# Generated by Django 3.2.6 on 2021-09-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_sale', '0012_order_i_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bought',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
