# Generated by Django 3.2.6 on 2021-09-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_sale', '0014_image_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='i_price',
            field=models.IntegerField(default=1),
        ),
    ]
