# Generated by Django 3.2.6 on 2021-09-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_sale', '0015_order_i_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='i_total_price',
            field=models.IntegerField(default=2),
        ),
    ]
