# Generated by Django 3.2.6 on 2021-09-24 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('com_sale', '0016_order_i_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expiration_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='listing_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='paid_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
