# Generated by Django 3.2.6 on 2021-09-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_sale', '0017_auto_20210924_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='listing_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='paid_date',
            field=models.DateTimeField(),
        ),
    ]
