# Generated by Django 3.2.6 on 2021-09-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_sale', '0018_auto_20210924_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='paid_date',
            field=models.IntegerField(),
        ),
    ]
