# Generated by Django 3.2.6 on 2021-09-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_sale', '0020_alter_item_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='paid_date',
            field=models.IntegerField(),
        ),
    ]
