# Generated by Django 3.2.6 on 2021-10-14 08:10

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('g_pigeon_race', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(default=1231, max_length=64)),
                ('value', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='fancier')),
            ],
        ),
        migrations.CreateModel(
            name='Userimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='fancier_profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Mypigeons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=24)),
                ('ring', models.CharField(max_length=24)),
                ('time', models.CharField(max_length=64)),
                ('link', models.ImageField(blank=True, default=None, max_length=64, null=True, storage=django.core.files.storage.FileSystemStorage(location='/user/pigeons/'), upload_to='')),
                ('loaded', models.BooleanField(default=False)),
                ('loads', models.CharField(blank=True, max_length=64)),
                ('my_lat', models.CharField(max_length=64)),
                ('my_long', models.CharField(max_length=64)),
                ('races', models.ManyToManyField(blank=True, related_name='registered', to='g_pigeon_race.Race')),
            ],
        ),
    ]
