# Generated by Django 3.2.6 on 2021-12-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='coin_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
