# Generated by Django 3.2.6 on 2021-09-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_chain_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='chain',
            field=models.CharField(default=1, max_length=64),
        ),
    ]
