# Generated by Django 3.2.6 on 2021-12-03 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_coin_coin_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coin',
            new_name='Order',
        ),
    ]
