# Generated by Django 3.2.6 on 2021-12-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_coin_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('hash', models.CharField(blank=True, max_length=64)),
                ('quantity', models.IntegerField(default=0)),
                ('coin', models.CharField(max_length=64)),
            ],
        ),
    ]
