# Generated by Django 3.2.6 on 2021-12-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_hash_user_coins_hashed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='coin',
            new_name='buy_coin',
        ),
        migrations.AddField(
            model_name='order',
            name='sell_coin',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
