# Generated by Django 3.2.6 on 2022-01-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_visitor',
            name='address',
            field=models.CharField(max_length=164),
        ),
        migrations.AlterField(
            model_name='user_visitor',
            name='contact',
            field=models.CharField(blank=True, max_length=164),
        ),
        migrations.AlterField(
            model_name='user_visitor',
            name='location',
            field=models.CharField(max_length=264),
        ),
    ]
