# Generated by Django 3.2.6 on 2021-12-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='reinvested',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='total_investment',
            name='average',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='total_investment',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
