# Generated by Django 3.2.6 on 2021-12-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0002_auto_20211226_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='reinvested',
            field=models.DateTimeField(blank=True),
        ),
    ]
