# Generated by Django 3.2.6 on 2022-04-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0003_alter_investor_reinvested'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('timestamp2', models.DateTimeField(auto_now_add=True)),
                ('investor_name', models.CharField(max_length=64)),
                ('invest_amount', models.FloatField()),
                ('invesotr_id', models.IntegerField()),
            ],
        ),
    ]
