# Generated by Django 3.2.6 on 2022-08-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0004_investmentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='invested_value',
            field=models.IntegerField(default=0),
        ),
    ]
