# Generated by Django 3.2.6 on 2022-08-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0005_investor_invested_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='StocksHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockQuantity', models.IntegerField()),
                ('stockBuyPrice', models.IntegerField()),
                ('stockName', models.CharField(max_length=64)),
            ],
        ),
    ]
