# Generated by Django 3.2.6 on 2022-08-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0007_auto_20220810_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentrecord',
            name='CurrentiClubValue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investmentrecord',
            name='investedPercentageAfter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investmentrecord',
            name='investedPercentageBefore',
            field=models.IntegerField(default=0),
        ),
    ]
