# Generated by Django 3.2.6 on 2022-08-10 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0009_investmentrecord_invest_valuebefore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentrecord',
            old_name='invesotr_id',
            new_name='investor_id',
        ),
    ]
