# Generated by Django 3.2.6 on 2022-08-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0010_rename_invesotr_id_investmentrecord_investor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalTransactionCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockName', models.CharField(max_length=32)),
                ('TransactionSide', models.CharField(max_length=32)),
                ('stockPrice', models.FloatField()),
                ('CostAfterTax', models.IntegerField()),
            ],
        ),
    ]
