# Generated by Django 3.2.6 on 2022-08-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0011_totaltransactioncost'),
    ]

    operations = [
        migrations.AddField(
            model_name='totaltransactioncost',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
