# Generated by Django 3.2.6 on 2022-08-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0015_auto_20220812_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='totaltransactionrecord',
            name='stockQuantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sidecomputations',
            name='sideAmount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sidecomputations',
            name='updatedTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
