# Generated by Django 3.2.6 on 2022-08-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0016_auto_20220812_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidecomputations',
            name='InterestComputation',
            field=models.FloatField(default=0),
        ),
    ]
