# Generated by Django 3.2.6 on 2022-08-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0017_sidecomputations_interestcomputation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidecomputations',
            name='ProfitComputation',
            field=models.IntegerField(default=0),
        ),
    ]
