# Generated by Django 3.2.6 on 2022-08-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0018_sidecomputations_profitcomputation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='total_investment',
            old_name='quantity',
            new_name='gatheredAmount',
        ),
        migrations.AlterField(
            model_name='sidecomputations',
            name='YearComputation',
            field=models.IntegerField(default=2022),
        ),
    ]
