# Generated by Django 3.2.6 on 2022-08-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0021_alter_investor_invested_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentrecord',
            name='invest_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='investmentrecord',
            name='investedPercentageAfter',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='investmentrecord',
            name='investedPercentageBefore',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='investor',
            name='invested_percentage',
            field=models.FloatField(default=0),
        ),
    ]
