# Generated by Django 3.2.6 on 2022-08-13 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0022_auto_20220812_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveDividends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractRatio', models.IntegerField(default=0)),
                ('valueDeducted', models.IntegerField(default=0)),
                ('dividendAmount', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterestTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('percentage', models.FloatField()),
                ('duration', models.CharField(blank=True, max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='investor',
            name='dividendsReceived',
            field=models.ManyToManyField(blank=True, related_name='dividendGiven', to='com_invest.GiveDividends'),
        ),
        migrations.AddField(
            model_name='investor',
            name='interestType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TypeofInterest', to='com_invest.interesttypes'),
        ),
    ]
