# Generated by Django 3.2.6 on 2022-08-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0023_auto_20220813_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='givedividends',
            old_name='dividendAmount',
            new_name='investedDividend',
        ),
        migrations.RemoveField(
            model_name='givedividends',
            name='valueDeducted',
        ),
        migrations.AddField(
            model_name='givedividends',
            name='investedAmount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='givedividends',
            name='investedProfit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='givedividends',
            name='investedValue',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
