# Generated by Django 3.2.6 on 2022-08-13 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0024_auto_20220813_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='interestType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TypeofInterest', to='com_invest.interesttypes'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='investor_contact',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
