# Generated by Django 3.2.6 on 2022-08-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0025_auto_20220813_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='investmentHistory',
            field=models.ManyToManyField(blank=True, related_name='investrecordhistory', to='com_invest.InvestmentRecord'),
        ),
    ]
