# Generated by Django 3.2.6 on 2022-08-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0027_auto_20220813_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='interestType',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
