# Generated by Django 3.2.6 on 2022-08-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0028_investor_interesttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interesttypes',
            name='GrowthInterest',
        ),
        migrations.AddField(
            model_name='givedividends',
            name='isGiven',
            field=models.BooleanField(default=False),
        ),
    ]
