# Generated by Django 3.2.6 on 2022-08-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0029_auto_20220813_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesttypes',
            name='GrowthInterest',
            field=models.ManyToManyField(blank=True, related_name='growthList', to='com_invest.Investor'),
        ),
    ]
