# Generated by Django 3.2.6 on 2022-08-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0030_interesttypes_growthinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='duration',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='investor',
            name='invested_amount',
            field=models.IntegerField(default=0),
        ),
    ]
