# Generated by Django 3.2.6 on 2022-08-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0031_auto_20220813_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='interest',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
