# Generated by Django 3.2.6 on 2022-08-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0032_alter_investor_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='givedividends',
            name='investorID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='givedividends',
            name='contractRatio',
            field=models.FloatField(default=0),
        ),
    ]
