# Generated by Django 3.2.6 on 2022-08-14 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0034_rename_givedividends_dividendrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dividendrecord',
            old_name='isGiven',
            new_name='deliveredDividend',
        ),
    ]
