# Generated by Django 3.2.6 on 2022-08-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0035_rename_isgiven_dividendrecord_delivereddividend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_investment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
