# Generated by Django 3.2.6 on 2022-08-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0036_alter_total_investment_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TotalTransactionRecord',
            new_name='TradeRecords',
        ),
    ]
