# Generated by Django 3.2.6 on 2022-08-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0037_rename_totaltransactionrecord_traderecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidecomputations',
            name='InterestComputation',
            field=models.DecimalField(decimal_places=4, max_digits=4),
        ),
    ]
