# Generated by Django 3.2.6 on 2022-08-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_invest', '0038_alter_sidecomputations_interestcomputation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidecomputations',
            name='InterestComputation',
            field=models.FloatField(default=0),
        ),
    ]
